version: "3"

services:
  api:
    image: eyesore/go:1.20
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    networks:
      - jan-galek.cz
    depends_on:
      - database

  database:
    image: postgres
    env_file:
      - .env

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - jan-galek.cz

networks:
  jan-galek.cz:
    external: true

volumes:
    pgdata: