version: "3"

services:
  api:
    build: .
    ports:
      - '8000:8000'
    networks:
      - jan-galek.cz
    depends_on:
      - database

  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - './temp/database:/var/lib/postgresql/data'


networks:
  jan-galek.cz:
    external: true
  